// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm7mH5Qgi_riPyogrWuSafMHPj8KiGBVY',
    appId: '1:737598601144:web:6ea87b8b1e1577d608014d',
    messagingSenderId: '737598601144',
    projectId: 'pdftotext-59667',
    authDomain: 'pdftotext-59667.firebaseapp.com',
    storageBucket: 'pdftotext-59667.appspot.com',
    measurementId: 'G-T45FXHLR71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsn1z6kkJ8EIIZmr-u_uhdbHTklP62PL8',
    appId: '1:737598601144:android:b9fa4bd7e721d45a08014d',
    messagingSenderId: '737598601144',
    projectId: 'pdftotext-59667',
    storageBucket: 'pdftotext-59667.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcqWU7ZBayHR9BANw0I26-KcwD2N_rITs',
    appId: '1:737598601144:ios:3dd3c75ec0e4caa808014d',
    messagingSenderId: '737598601144',
    projectId: 'pdftotext-59667',
    storageBucket: 'pdftotext-59667.appspot.com',
    iosBundleId: 'com.example.doj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcqWU7ZBayHR9BANw0I26-KcwD2N_rITs',
    appId: '1:737598601144:ios:3dd3c75ec0e4caa808014d',
    messagingSenderId: '737598601144',
    projectId: 'pdftotext-59667',
    storageBucket: 'pdftotext-59667.appspot.com',
    iosBundleId: 'com.example.doj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm7mH5Qgi_riPyogrWuSafMHPj8KiGBVY',
    appId: '1:737598601144:web:9dc455cafb7c36cd08014d',
    messagingSenderId: '737598601144',
    projectId: 'pdftotext-59667',
    authDomain: 'pdftotext-59667.firebaseapp.com',
    storageBucket: 'pdftotext-59667.appspot.com',
    measurementId: 'G-W46TECT8Q3',
  );
}
